### ISSUE TITLE
Apps could't be download from Google Play Store

### ISSUE THREAD

**Issue by delphinuz** [MSF-Jarvis/wireguard-kt#22]
Download function in user app like telegram or browser can work, but it can't work in Google Play Store.

**Comment by MSF-Jarvis** [comment]
I don't understand this issue at all. Are you having connectivity problems? Those are related to your provider and not the app. Raise a support ticket with them if you can't debug it on your end and close this issue.

**Comment by delphinuz** [comment]
I did many test. Only Download Manager can't download files when wireguard was enabled. All other apps can download files as normally.

My location is in China, maybe it's dns issue.

**Comment by delphinuz** [comment]
Just found Download Manager can work if wireguard is in non-root mode.

**Comment by MSF-Jarvis** [comment]
![](https://camo.githubusercontent.com/24d7e729cf89ca7b971ae16fe42e6ffc4c7077a4/68747470733a2f2f7777772e6c656164696e676167696c652e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031372f30332f776f726b736f6e6d796d616368696e652e706e67)

**Comment by Love4Taylor** [comment]
Same here, Did you solve this?

logcat with wireguarid kernel module
```
10-21 09:19:46.605 30981  4907 W DownloadManager: [514] Stop requested with status HTTP_DATA_ERROR: SSL handshake aborted: ssl=0x766f2a4008: I/O error during system call, Connection reset by peer
10-21 09:19:46.609 30981  4907 D DownloadManager: [514] Finished with status WAITING_TO_RETR
```
