### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by splendidbits** [MSF-Jarvis/wireguard-kt#44]
Do you need any help at all with the UI, more specifically a good icon? You'd keep all rights.

Some of my stuff:
https://play.google.com/store/apps/developer?id=Daniel+Watson

**Comment by MSF-Jarvis** [comment]
About UI, getting #43 in a mergeable state would be a great start.

About the icon, I'm not very sure. I do like the idea of having a differentiation from the official client but I don't know what you have in mind. Open a PR with what you're thinking and let's take it from there?

**Comment by splendidbits** [comment]
Here's something I threw together. If you like it, it would be fun to help with other parts of the UI.

Feedback welcome :)

![wireguard-kt](https://user-images.githubusercontent.com/444335/46263634-7a58aa80-c4c6-11e8-8a08-fa2fa976aa3b.png)

**Comment by splendidbits** [comment]
Here's something I threw together. If you like it, it would be fun to help with other parts of the UI.

Feedback welcome :)

![wireguard-kt](https://user-images.githubusercontent.com/444335/46263648-ab38df80-c4c6-11e8-99fd-a1b751aa9286.png)

**Comment by MSF-Jarvis** [comment]
I like it! I'll have my testers share their opinion on the icon and get back to you with what they say.

**Comment by splendidbits** [comment]
@MSF-Jarvis Awesome. PR incoming

**Comment by splendidbits** [comment]
After the honest and true feedback the PR was closed, although I think a lot of work has been put into this rewrite and it deserves its own icon, color scheme, etc. 

https://github.com/MSF-Jarvis/wireguard-kt/pull/48#issuecomment-426053001
