### ISSUE TITLE
Android VPN authorisation prompt not invoked when importing previous configurations.

### ISSUE THREAD

**Issue by splendidbits** [MSF-Jarvis/wireguard-kt#45]
As the title says: In order for the invocation of the VPN creation dialogue, an attribute in the imported configuration has to first be edited.

**Comment by MSF-Jarvis** [comment]
I tried to reproduce the issue on my Nubia Red Magic running Android 8.1 by removing the VPN from the system, reimporting all my tunnels and then trying to enable one and it showed me the authorisation dialog just fine. Can you provide some more information like device, Android version and the like?

**Comment by splendidbits** [comment]
Did you try also removing the VPN config from Settings > Network -> VPN

**Comment by MSF-Jarvis** [comment]
@splendidbits that was what I meant by "removing the VPN from the system", sorry if it wasn't clear enough.

**Comment by splendidbits** [comment]
No worries! I'll try and recreate it again, but there's an issue there somewhere :)

**Comment by MSF-Jarvis** [comment]
Closing until we have more reliable reproduction steps for the problem.
