### ISSUE TITLE
Gradle Version Inconsistency

### ISSUE THREAD

**Issue by theLimitBreaker** [MSF-Jarvis/wireguard-kt#51]
Gradle plugin 3.3.0-alpha12

gradle-wrapper.properties 
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

this works with Canary Channel of android studio

and produce this error
`Unsupported method: NativeArtifact.getSourceFolders(). The version of Gradle you connect to does not support that method. To resolve the problem you can change/upgrade the target version of Gradle you connect to. Alternatively, you can ignore this exception and read other information from the model`

##### Steps to reproduce 
try to do gradle sync with above configurations in stable realease of android studio

##### Solution
Please add both versions of gradle for Canary and Stable channel of Android Studio in README.md . Then the concerned developer can pick version of gradle according to her/his version of android studio

**Comment by MSF-Jarvis** [comment]
Worked for me on stable couple days ago IIRC but feel free to include a patch resetting the plugin to `3.2.0` in your PR.
