### ISSUE TITLE
Flawed custom font

### ISSUE THREAD

**Issue by kdrag0n** [MSF-Jarvis/wireguard-kt#79]
The new custom in-app Actor font has uneven number positioning like Raleway. Switch to a font with consistent numbering. For example, Raleway's edit called [Rawline](https://h-ibaldo.github.io/Raleway_Fixed_Numerals/) fixes it. I don't think this is acceptable for an app with numbers...

![](https://i.imgur.com/XMmwUwy.jpg)

**Comment by MSF-Jarvis** [comment]
This is not merged into master, please move this to a comment in the PR that was left open for precisely this purpose 🙁
